### ISSUE TITLE
Ansible setup for Redpanda-console

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/deployment-automation#169] opened 2023-04-13 00:35 UTC
We need a role for deploying redpanda-console. 

We'll need to use the same setup.sh scripts as redpanda_broker to make sure we get the repos instantiated.

Starter config will need at least the broker list in /etc/redpanda/redpanda-console-config.yaml.

we'll need to make sure systemd config is enabled and started.

Would be nice to support multiple console instances (on multiple machines). these are stateless.

**Comment by hcoyote** [comment] 2023-04-13 19:27
We'll need to do something similar with the redpanda-console-config.yaml as we do with the redpanda.yaml for integrating overrides from ansible. 

So, a config template like

https://github.com/redpanda-data/deployment-automation/blob/a5499a9a61c8fdd8ccd526cbd9c7abafe22d200f/ansible/roles/redpanda_broker/templates/redpanda.yml#L1

and config setup/merging like
https://github.com/redpanda-data/deployment-automation/blob/a5499a9a61c8fdd8ccd526cbd9c7abafe22d200f/ansible/roles/redpanda_broker/tasks/start-redpanda.yml#L12-L35

Also need to figure out how to integrate with a running connectors setup. since connectors only run within a container, maybe a playbook that stubs out a docker install and pulls the image over. Not sure.

**Comment by tmgstevens** [comment] 2023-04-14 12:34
Dupe of #73

**Comment by gene-redpanda** [comment] 2023-04-21 16:25
From comment in duplicate issue: 

This needs a change in the terraform scripts as well.

An example of how the playbook would look like: https://redpandacommunity.slack.com/archives/C039U14NY04/p1662538501878789?thread_ts=1662124131.079259&cid=C039U14NY04

**Closed** 2024-07-02 16:17 UTC
